import pyautogui, time

def abrirCalculadora():
    pageDown()
    time.sleep(0.2)
    pyautogui.press(['win'])
    time.sleep(2)
    pyautogui.write('calculadora')
    time.sleep(1.1)
    pyautogui.press(['enter'])
    time.sleep(1.5)
    pyautogui.keyDown('win')
    pyautogui.press(['right'])
    time.sleep(0.2)
    pyautogui.keyUp('win')
    time.sleep(0.2)
    pyautogui.moveTo(['1303', '49'])
    time.sleep(0.2)
    pyautogui.click()
    time.sleep(0.2)
    pageUp()

def ctrlC():
    pyautogui.keyDown('ctrlleft')
    pyautogui.press(['c'])
    time.sleep(0.5)
    pyautogui.keyUp('ctrlleft')

def ctrlV():
    pyautogui.keyDown('ctrlleft')
    pyautogui.press(['v'])
    time.sleep(0.5)
    pyautogui.keyUp('ctrlleft')

def pageDown():
    pyautogui.keyDown('win')
    pyautogui.press(['pagedown'])
    time.sleep(0.5)
    pyautogui.keyUp('win')

def pageUp():
    pyautogui.keyDown('win')
    pyautogui.press(['pageup'])
    time.sleep(0.5)
    pyautogui.keyUp('win')

pyautogui.alert('Agora o computador está sendo controlado')

pyautogui.PAUSE = 0.5
abrirCalculadora()
pyautogui.keyDown('alt')
pyautogui.press(['tab'])
pyautogui.keyUp('alt')
while True:
    time.sleep(1)
    pyautogui.moveTo(['1357', '449'])
    pyautogui.click()
    pyautogui.moveTo(['1196', '385'])
    pyautogui.click()
    time.sleep(4)
    pyautogui.moveTo(['1359', '163'])
    pyautogui.click()
    time.sleep(20)
    pyautogui.moveTo(['1359', '163'])
    pyautogui.click()
    time.sleep(20)
    pyautogui.moveTo(['1359', '163'])
    pyautogui.click()
    time.sleep(30)
    pyautogui.moveTo(['907', '169'])
    pyautogui.doubleClick()
    ctrlC()
    pageDown()
    time.sleep(1)
    ctrlV()
    time.sleep(1)
    pyautogui.click(['798', '739'])
    pageUp()
    pyautogui.moveTo(['985', '169'])
    pyautogui.doubleClick()
    time.sleep(0.3)
    ctrlC()
    pageDown()
    time.sleep(0.3)
    ctrlV()
    time.sleep(0.3)
    pyautogui.click(['1127', '741'])
    time.sleep(0.3)
    pyautogui.moveTo(['19', '560'])
    time.sleep(0.3)
    pyautogui.doubleClick()
    time.sleep(0.3)
    ctrlC()
    pyautogui.press(['delete'])
    time.sleep(0.3)
    pageUp()
    time.sleep(0.2)
    pyautogui.click(['1066', '169'])
    time.sleep(0.2)
    ctrlV()
    pyautogui.moveTo(['1184', '177'])
    pyautogui.doubleClick()
    time.sleep(5)